name: My GitHub Action
description: How to Use SCP Command to Transfer Files/Folders in Linux.
author: Tarene Durgapershad
inputs:
  my_input:
    description: 'An example input'
    required: true
    default: 'Default value'
runs:
  using: 'node12'
  main: 'index.js'
